In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import xlwt
from datetime import datetime
import matplotlib.dates as mdate 
import matplotlib.ticker as ticker
import matplotlib.mlab as mlab
from pylab import mpl
import os
import seaborn as sns
from statsmodels.formula.api import ols
import sklearn
import math
import scipy as sp

In [5]:
f0 = pd.DataFrame(pd.read_csv('dataflow_010.csv',sep = ',',encoding='utf-8'))
pd.set_option('precision', 7)
f0['ts']=pd.to_datetime(f0['Data'],format=u'%Y\u5e74%m\u6708%d\u65e5')
f1 = f0.drop(['Data'],axis = 1)
f2=f1.set_index(f0['ts'])
f2.index.rename('Date',inplace = True)
f3=f2.drop(f2.columns[-1],axis = 1)
f4 = f3.sort_index()
# dataflow = f4['DataflowByDay_4G_GB']
# data_mean=dataflow.mean()
# data_std=dataflow.std()
#f5=f4[f4['DataflowByDay_4G_GB']>=(data_mean-1.96*data_std)]
# f4['DataflowByDay_4G_GB'] = f4['DataflowByDay_4G_GB']/8

In [151]:
# f5.to_csv('Revised_dataflow_011.csv')

In [6]:
f9 = pd.DataFrame(pd.read_excel(u'国庆节数据.xlsx',sep = '|',encoding='utf-8'))
df1 = pd.DataFrame(pd.read_excel(u'16.39.xlsx',sep = '|',encoding='utf-8'))
pd.set_option('precision', 7)
f10 = f9.groupby(u'地市')
df2 = df1.groupby(u'地市')
df2

In [7]:
for name,groupData in f10:
    if name.encode('utf-8') == '徐州':
        f5 = pd.DataFrame(groupData)
        f5.rename(columns={u'时间':'Date',u'流量（GB）':'DataflowByDay_4G_GB'},inplace = True)
        f5.drop(u'地市',axis = 1, inplace = True)
        f6 = f5.set_index(pd.to_datetime(f5['Date']))
        f6.drop('Date',axis = 1, inplace = True)
        f7 = pd.concat([f4,f6],ignore_index= False)
        f8 = f7.sort_index()
        dataflow = f8['DataflowByDay_4G_GB']
        data_mean=dataflow.mean()
        data_std=dataflow.std()
#         f11=f8[f8['DataflowByDay_4G_GB']>=(data_mean-1.96*data_std)]
for name1,groupData1 in df2:
    if name1.encode('utf-8') == '徐州':
        df5 = pd.DataFrame(groupData1)
        df5.rename(columns={u'时间':'Date',u'流量（Gb）':'DataflowByDay_4G_GB'},inplace = True)
        df5.drop(u'地市',axis = 1, inplace = True)
        df5['time'] = df5['Date'].apply(lambda x:str(x.encode('utf-8')).split()[0])
        df5.index = pd.to_datetime(df5['time'])
        df5.drop({'Date','time'},axis = 1, inplace = True)
        df5.index.rename('Date',inplace = True)
        df5['DataflowByDay_4G_GB'] = df5['DataflowByDay_4G_GB']/8
        df7 = pd.concat([f8,df5],ignore_index= False)        
        df8 = df7.sort_index()
        dataflow = df8['DataflowByDay_4G_GB']
        data_mean=dataflow.mean()
        data_std=dataflow.std()
#         df10=df8[df8['DataflowByDay_4G_GB']>=(data_mean-1.96*data_std)]
        pd.set_option('precision', 7)
        df8.to_csv(u'data010.csv',encoding='utf-8')

In [19]:
pd.set_option('precision', 11)
df8

            DataflowByDay_4G_GB
Date
2016-03-01    6.20759369250e+04
2016-03-02    6.32090255875e+04
2016-03-03    6.41530306500e+04
2016-03-04    6.43486821875e+04
2016-03-05    6.42007511500e+04
2016-03-06    6.21466673750e+04
2016-03-07    6.26081917750e+04
2016-03-08    6.63919049250e+04
2016-03-09    6.13035647625e+04
2016-03-10    6.02812129625e+04
2016-03-11    5.80565945500e+04
2016-03-12    6.11886756125e+04
2016-03-13    6.19362163000e+04
2016-03-14    5.97024134875e+04
2016-03-15    6.12426866625e+04
2016-03-16    5.93848972750e+04
2016-03-17    6.19675531375e+04
2016-03-18    6.26457746250e+04
2016-03-19    6.15161233500e+04
2016-03-20    5.92956091625e+04
2016-03-21    5.74005514375e+04
2016-03-22    5.92876708000e+04
2016-03-23    5.99049080250e+04
2016-03-24    6.32353890000e+04
2016-03-25    6.12257211000e+04
2016-03-26    6.00780581500e+04
2016-03-27    5.94578359125e+04
2016-03-28    5.85017411750e+04
2016-03-29    5.90553571500e+04
2016-03-30    6.07498101000e+04
...                         ...
2017-09-10    2.17572083900e+06
2017-09-11    1.84395640500e+06
2017-09-12    1.96101901000e+06
2017-09-13    1.92811293700e+06
2017-09-14    1.92121672000e+06
2017-09-15    2.02670793100e+06
2017-09-16    2.11126496200e+06
2017-09-17    2.09324413800e+06
2017-09-18    2.00208150000e+06
2017-09-19    2.06506303800e+06
2017-09-20    2.12342574100e+06
2017-09-21    2.64072132003e+05
2017-09-22    2.64798451938e+05
2017-09-23    2.72753484012e+05
2017-09-24    2.73484587966e+05
2017-09-25    2.82434914296e+05
2017-09-26    2.96783931156e+05
2017-09-27    2.83149335611e+05
2017-09-28    2.59918990734e+05
2017-09-29    2.93586734754e+05
2017-09-30    3.22880517727e+05
2017-10-01    2.99258112511e+05
2017-10-02    2.89552458490e+05
2017-10-03    3.03814725982e+05
2017-10-04    3.17574753978e+05
2017-10-05    2.97733284640e+05
2017-10-06    2.76907653129e+05
2017-10-07    2.73991803106e+05
2017-10-08    2.77041775720e+05
2017-10-09    2.62021717354e+05

[582 rows x 1 columns]

In [23]:
f11 = pd.DataFrame(pd.read_csv('re000.csv',sep = ',',encoding='utf-8'))
f11['ts']=pd.to_datetime(f11['Date'])
f12 = f11.set_index('ts')
f12.drop('Date',axis = 1,inplace= True)

In [26]:
f13 = f12.groupby(pd.TimeGrouper("M"))
for i,j in f13:
    print i,j
    break

2016-03-31 00:00:00             DataflowByDay_4G_GB
ts
2016-03-01         63496.391863
2016-03-02         65972.958375
2016-03-03         66935.481825
2016-03-04         67601.279787
2016-03-05         64668.970013
2016-03-06         64690.947712
2016-03-07         65034.423888
2016-03-08         68391.498487
2016-03-09         63338.067738
2016-03-10         64046.242950
2016-03-11         61585.509875
2016-03-12         62198.794075
2016-03-13         62137.063562
2016-03-14         61298.537350
2016-03-15         63341.760150
2016-03-16         64492.917725
2016-03-17         63572.219575
2016-03-18         66142.756663
2016-03-19         64022.692087
2016-03-20         62296.057587
2016-03-21         62210.870700
2016-03-22         63129.985163
2016-03-23         62547.298300
2016-03-24         64478.351087
2016-03-25         62313.991738
2016-03-26         61393.333375
2016-03-27         60274.076625
2016-03-28         57724.620537
2016-03-29         62266.536050
2016-03-30         63101.349412
2016-03-31         68093.476837

In [113]:
(f11[['DataflowByDay_4G_GB']]==0).sum()

DataflowByDay_4G_GB    2
dtype: int64

In [105]:
# f12 = f11[f11.columns[2] == 0]
f12 = f11[f11[f11.columns[1]] == 0]

In [11]:
df1 = pd.DataFrame(pd.read_excel('20171215104356649.xlsx',sep = ',',columns={0,1,2}))

In [13]:
df1.head(10)

,时间,地市名称,省名称,下行PDCCH CCE利用率,上行PRB平均利用率(集团),下行PRB平均利用率(集团),LTE无线利用率(集团),LTE总流量(Gb),E-RAB建立成功数(QCI=1),E-RAB建立成功数(QCI=2),...,VoLTE语音总流量(GB),volte视频话务量(Erl),VoLTE语音话务量(Erl),volte视频总流量(GB),上行用户面丢包率,下行用户面丢包率,上行用户面丢包率(QCI=1),上行用户面丢包率(QCI=2),下行用户面丢包率(QCI=1),下行用户面丢包率(QCI=2)
0,2016-12-23 04:00:00,常州,江苏,2.69%,0.48%,2.02%,5.37%,7409.7775,3105,2,...,0.68,0.00,47.90,0.0,0.12%,0.02%,0.15%,0.00%,0.25%,0.00%
1,2016-12-23 04:00:00,淮安,江苏,2.38%,1.54%,1.92%,4.76%,3792.6058,2318,1,...,0.28,0.00,35.27,0.0,0.01%,0.01%,0.59%,0.00%,0.17%,0.00%
2,2016-12-23 04:00:00,南京,江苏,1.87%,0.54%,1.63%,3.74%,15493.9238,5791,2,...,0.67,0.00,93.14,0.0,0.01%,0.00%,0.13%,0.00%,0.18%,0.00%
3,2016-12-23 04:00:00,南通,江苏,3.05%,0.92%,1.92%,6.11%,8627.4571,4515,5,...,0.85,0.00,66.65,0.0,0.10%,0.05%,0.07%,0.00%,0.16%,0.00%
4,2016-12-23 04:00:00,江苏,江苏,2.78%,1.16%,1.86%,5.56%,117878.5072,43356,40,...,7.09,0.03,690.78,0.0,0.04%,0.01%,0.21%,0.00%,0.18%,0.00%
5,2016-12-23 04:00:00,苏州,江苏,3.88%,1.88%,2.15%,7.76%,32650.5082,9346,8,...,1.33,0.02,145.95,0.0,0.04%,0.02%,0.06%,0.00%,0.13%,0.00%
6,2016-12-23 04:00:00,宿迁,江苏,3.12%,1.36%,1.78%,6.23%,4646.8508,2147,0,...,0.34,0.00,42.78,0.0,0.01%,0.01%,0.33%,0.00%,0.28%,0.00%
7,2016-12-23 04:00:00,泰州,江苏,2.60%,1.45%,1.74%,5.20%,4293.1985,917,1,...,0.08,0.00,11.78,0.0,0.00%,0.00%,0.04%,0.00%,0.06%,0.00%
8,2016-12-23 04:00:00,无锡,江苏,3.44%,1.30%,1.86%,6.88%,14128.7037,4514,1,...,0.75,0.00,70.57,0.0,0.11%,0.01%,0.17%,0.00%,0.19%,0.00%
9,2016-12-23 04:00:00,徐州,江苏,1.34%,0.90%,1.67%,3.35%,8262.1969,2853,12,...,0.91,0.00,63.40,0.0,0.01%,0.00%,0.82%,0.00%,0.24%,0.00%